### ISSUE TITLE
`pnpm build-all` fails on Windows due to single quotes in webview project.json

### ISSUE THREAD

**Issue by euvinkeel** [trypear/pearai-extension#22]
## Describe the bug
When running `pnpm build-all` on a Windows environment, the build fails with the following error:

```
×  nx run webview:build
       ✘ [ERROR] Unexpected single quote character before flag: '--define:process.env.NODE_ENV=production'

  This typically happens when attempting to use single quotes to quote arguments with a shell that doesn't recognize single quotes. Try using double quote characters to quote arguments instead.
```

## How to reproduce
On Windows 10: (changed the git clone link to github's provided HTTPS link)
Clone the repo: git clone https://github.com/trypear/pearai-extension.git
Go into the cloned repository: cd pearai-extension
Install dependencies: pnpm install
Build the extension: pnpm build-all

## Expected behavior
To successfully build with `pnpm build-all` after successfully cloning the repo and running `pnpm install`

## Screenshots
N/A

## Additional information
N/A

**Comment by Fryingpannn** [comment]
CAN ANYONE ELSE USING WINDOWS CONFIRM THIS

**Comment by Fryingpannn** [comment]
FIRST CONTRIBUTOR PR!!!!!!!

**Comment by abdealijaroli** [comment]
> THANK YOU. CAN ANYONE ELSE USING WINDOWS CONFIRM THIS

os: win11
the fix works. attaching the screenshot below.
![image](https://github.com/trypear/pearai-extension/assets/56578305/521e104a-f91f-440f-b926-a0d8cdbf5769)

**Comment by Fryingpannn** [comment]
THANK YOU  cc: @ItWasEnder
